import { escapeHtml, renderSelectOptions } from "./shared"
import type { ExistingHierarchyEditorViewModel } from "./types"

export const renderExistingHierarchyNodeEditor = (viewModel: ExistingHierarchyEditorViewModel): string => {
  if (viewModel.kind === "effect") {
    return `
      <section class="asset-child-creator__form">
        <section class="asset-child-creator__section">
          <header class="asset-child-creator__section-head">
            <strong class="asset-child-creator__section-title">Definition</strong>
          </header>
          <label class="field field--full">
            <span>${viewModel.requiredEffectLabel}</span>
            <select id="childCreatorEffectOptionInput" required>
              <option value="">Select effect</option>
              ${renderSelectOptions(viewModel.effectOptions)}
            </select>
          </label>
        </section>
        <div class="asset-child-creator__actions">
          <button id="cancelChildCreatorButton" class="secondary-button" type="button">Cancel</button>
          <button id="createChildButton" class="primary-button" type="button" ${viewModel.saveDisabled ? "disabled" : ""}>Save</button>
        </div>
      </section>
    `
  }

  if (viewModel.kind === "autoGenerated") {
    return `
      <section class="asset-child-creator__form">
        <section class="asset-child-creator__section">
          <header class="asset-child-creator__section-head">
            <strong class="asset-child-creator__section-title">Definition</strong>
          </header>
          <div class="asset-child-creator__preview-grid">
            <div class="asset-child-creator__preview-item">
              <span>Name</span>
              <strong>${escapeHtml(viewModel.fullCode)}</strong>
            </div>
          </div>
          <label class="field field--full">
            <span>${viewModel.requiredDescriptionLabel}</span>
            <input
              id="childCreatorDescriptionInput"
              type="text"
              value="${escapeHtml(viewModel.description)}"
              placeholder="${escapeHtml(viewModel.descriptionPlaceholder)}"
              required
            >
          </label>
        </section>
        <div class="asset-child-creator__actions">
          <button id="cancelChildCreatorButton" class="secondary-button" type="button">Cancel</button>
          <button id="createChildButton" class="primary-button" type="button" ${viewModel.saveDisabled ? "disabled" : ""}>Save</button>
        </div>
      </section>
    `
  }

  return `
    <section class="asset-child-creator__form">
      <section class="asset-child-creator__section">
        <header class="asset-child-creator__section-head">
          <strong class="asset-child-creator__section-title">Definition</strong>
        </header>
        <div class="asset-child-creator__row-grid">
          <label class="field">
            <span>${viewModel.requiredNameLabel}</span>
            <div class="hierarchy-code-field ${viewModel.inheritedPrefix ? "has-prefix" : ""}">
              <span class="hierarchy-code-field__prefix">${escapeHtml(viewModel.inheritedPrefix)}</span>
              <input id="childCreatorNameInput" type="text" value="${escapeHtml(viewModel.codeSegment)}" placeholder="Enter code segment" required>
            </div>
          </label>
          <label class="field">
            <span>${viewModel.requiredDescriptionLabel}</span>
            <input id="childCreatorDescriptionInput" type="text" value="${escapeHtml(viewModel.description)}" placeholder="Enter description" required>
          </label>
        </div>
      </section>
      <div class="asset-child-creator__actions">
        <button id="cancelChildCreatorButton" class="secondary-button" type="button">Cancel</button>
        <button id="createChildButton" class="primary-button" type="button" ${viewModel.saveDisabled ? "disabled" : ""}>Save</button>
      </div>
    </section>
  `
}
