import { describe, expect, it } from "vitest"
import { renderCauseConfigEditor } from "./cause"
import { renderEquipmentInfoEditor } from "./equipment"
import { renderExistingHierarchyNodeEditor } from "./hierarchy"

describe("standalone editor renderers", () => {
  it("renders equipment editor hooks", () => {
    const html = renderEquipmentInfoEditor({
      requiredNameLabel: 'Name <em class="field-required" aria-hidden="true">*</em><span class="sr-only">required</span>',
      requiredDescriptionLabel: 'Description <em class="field-required" aria-hidden="true">*</em><span class="sr-only">required</span>',
      parentPrefix: "AREA-SYS-",
      codeSegment: "EQ01",
      description: "Main Conveyor",
      equipmentFunction: "Move ore",
      equipmentType: "Conveyor",
      operatingContext: "Primary stream",
      effectPerHourDownOptions: [{ value: "High", label: "High", selected: true }],
      demandFrequencyOptions: [{ value: "Low", label: "Low", selected: true }],
      redundancyOptions: [{ value: "None", label: "None", selected: true }],
      redundancyMode: "None",
      redundancyPercent: "",
      maeCategoryOptions: [{ value: "No", label: "No", selected: true }],
      criticalityOptions: [{ value: "A", label: "A", selected: true }],
      saveDisabled: false,
    })

    expect(html).toContain('id="equipmentInfoCodeSegmentInput"')
    expect(html).toContain('id="equipmentInfoDescriptionInput"')
    expect(html).toContain('id="equipmentInfoEffectInput"')
    expect(html).toContain('id="saveEquipmentInfoButton"')
    expect(html).toContain('id="cancelEquipmentInfoEditButton"')
  })

  it("renders cause editor shell and injected fields markup", () => {
    const html = renderCauseConfigEditor({
      fullCode: "AREA-SYS-FM01",
      requiredComponentNameLabel: 'Component Name <em class="field-required" aria-hidden="true">*</em><span class="sr-only">required</span>',
      requiredDescriptionLabel: 'Failure Mode Description <em class="field-required" aria-hidden="true">*</em><span class="sr-only">required</span>',
      componentName: "Motor",
      description: "Fails to start",
      fieldsMarkup: '<section class="asset-child-creator__section"><button data-toggle-cause-advanced="edit">Advanced</button></section>',
      saveDisabled: true,
    })

    expect(html).toContain('id="causeConfigComponentNameInput"')
    expect(html).toContain('id="causeConfigDescriptionInput"')
    expect(html).toContain('data-toggle-cause-advanced="edit"')
    expect(html).toContain('id="saveCauseConfigButton"')
    expect(html).toContain('id="resetCauseConfigButton"')
  })

  it("renders effect editor variant", () => {
    const html = renderExistingHierarchyNodeEditor({
      kind: "effect",
      requiredEffectLabel: '<span class="field-label field-label--required">Effect</span>',
      effectOptions: [{ value: "EFF1", label: "EFF1 - Impact", selected: true }],
      saveDisabled: false,
    })

    expect(html).toContain('id="childCreatorEffectOptionInput"')
    expect(html).toContain('id="createChildButton"')
    expect(html).toContain('id="cancelChildCreatorButton"')
  })

  it("renders auto-generated editor variant", () => {
    const html = renderExistingHierarchyNodeEditor({
      kind: "autoGenerated",
      fullCode: "AREA-SYS-AUTO",
      requiredDescriptionLabel: '<span class="field-label field-label--required">Description</span>',
      description: "Generated description",
      descriptionPlaceholder: "Enter auto description",
      saveDisabled: false,
    })

    expect(html).toContain("AREA-SYS-AUTO")
    expect(html).toContain('id="childCreatorDescriptionInput"')
  })

  it("renders standard editor variant", () => {
    const html = renderExistingHierarchyNodeEditor({
      kind: "standard",
      inheritedPrefix: "AREA-SYS-",
      requiredNameLabel: '<span class="field-label field-label--required">Name</span>',
      requiredDescriptionLabel: '<span class="field-label field-label--required">Description</span>',
      codeSegment: "NODE1",
      description: "Node description",
      saveDisabled: true,
    })

    expect(html).toContain('id="childCreatorNameInput"')
    expect(html).toContain('id="childCreatorDescriptionInput"')
    expect(html).toContain('disabled')
  })
})
