export interface EditorSelectOptionViewModel {
  value: string
  label: string
  selected: boolean
  disabled?: boolean
}

export interface EquipmentInfoEditorViewModel {
  requiredNameLabel: string
  requiredDescriptionLabel: string
  parentPrefix: string
  codeSegment: string
  description: string
  equipmentFunction: string
  equipmentType: string
  operatingContext: string
  effectPerHourDownOptions: EditorSelectOptionViewModel[]
  demandFrequencyOptions: EditorSelectOptionViewModel[]
  redundancyOptions: EditorSelectOptionViewModel[]
  redundancyMode: string
  redundancyPercent: string
  maeCategoryOptions: EditorSelectOptionViewModel[]
  criticalityOptions: EditorSelectOptionViewModel[]
  saveDisabled: boolean
}

export interface CauseConfigEditorViewModel {
  fullCode: string
  requiredComponentNameLabel: string
  requiredDescriptionLabel: string
  componentName: string
  description: string
  fieldsMarkup: string
  saveDisabled: boolean
}

export interface ExistingHierarchyEffectOptionViewModel extends EditorSelectOptionViewModel {}

export type ExistingHierarchyEditorViewModel =
  | {
      kind: "effect"
      requiredEffectLabel: string
      effectOptions: ExistingHierarchyEffectOptionViewModel[]
      saveDisabled: boolean
    }
  | {
      kind: "autoGenerated"
      fullCode: string
      requiredDescriptionLabel: string
      description: string
      descriptionPlaceholder: string
      saveDisabled: boolean
    }
  | {
      kind: "standard"
      inheritedPrefix: string
      requiredNameLabel: string
      requiredDescriptionLabel: string
      codeSegment: string
      description: string
      saveDisabled: boolean
    }
